### ISSUE TITLE
Icon is not displaying in Menu Bar

### ISSUE THREAD

**Issue by ohararyan** [jonathontoon/tweet-tray#108]
## Expected Behavior

Icon should be visible in the menu bar at all times.

## Current Behavior
After opening the app the icon is no visible until clicking on the space where it should be at which point it is highlighted and displays the active state.

![screenshot 2018-02-12 17 53 05](https://user-images.githubusercontent.com/1509309/36084058-43870cb6-101e-11e8-8097-49020c53f23a.png)

![screenshot 2018-02-12 17 53 11](https://user-images.githubusercontent.com/1509309/36084059-43add5e4-101e-11e8-979d-e2c865d761d3.png)

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | v1.0.3
| Operating System | MacOS 10.13.2

**Comment by jonathontoon** [comment]
Thanks for the report @ohararyan. I'm currently on a machine running 10.13.3 without any issues, and unfortunately don't have access to an older OS so I'm unable to test it. It could be related to upgrading to the newest version of Electron though. 

Perhaps try running 1.0.2 or 1.0.1 and let me know if you're having the same issue. Otherwise if you have a chance to pull `develop` and poke around feel free to submit a fix!

**Comment by riotherio** [comment]
Running on 10.13.3, no issues!

**Comment by riotherio** [comment]
@ohararyan Any chances you are running a menu bar management software ore any UI customizations?

**Comment by ohararyan** [comment]
@riotherio interestingly yes! Looks like I had an old process of https://github.com/sindresorhus/dark-mode running which wasn't actually making the menu bar dark.

Turning dark-mode off returned the UI to the correct state and the menu icon displayed again.
Updating dark-mode has also fixed and displays the icons correctly when turning dark-mode on.

Thanks @riotherio for pointing that out. @jonathontoon probably safe to close this issue.

**Comment by jonathontoon** [comment]
Cheers for the follow up @ohararyan.
